### ISSUE TITLE
Permit acceptor process to recieve other messages

### ISSUE THREAD

**Issue by lpil** [rawhat/glisten#11]
Currently the acceptor process can only accept messages from the socket. There is no way for any other parts of the application to send an Erlang message to the acceptor process.

This means that the process can only do request-response messaging. It is not possible to (for example) implement pubsub, or anything else where it is driven not by the client, like a video game or stream of data.

This is the roughly same problem as Mist has with websockets.

**Comment by rawhat** [comment]
Just to make sure I'm understanding, you mean the individual handler processes, right?  If so, that definitely makes sense to me.

Separately, I do think it'd be useful to have the acceptor process able to receive other messages, but likely just for the graceful shutdown at the moment.

**Comment by lpil** [comment]
Yes, that's right 💜

**Comment by rawhat** [comment]
This is done 😄
