### ISSUE TITLE
UDP support?

### ISSUE THREAD

**Issue by Lilja-at-funnel** [rawhat/glisten#18]
Hi!

Is there any support for glisten to do listen for UDP traffic? Thanks

**Comment by rawhat** [comment]
The structure of this library is pretty tied to how TCP works.  It's crossed my mind to try to make it agnostic, but I'm not really sure how possible that is.  Or really how much I want to try to rewrite this to handle that.

I published a super [barebones UDP server](https://github.com/rawhat/grammy).  I honestly haven't used UDP in any capacity for a long time, and even then it wasn't very much.  So I don't know how good it is 😅 I'm definitely open to issues there!
